apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-mysql
  namespace: jhipster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tienda-mysql
  template:
    metadata:
      labels:
        app: tienda-mysql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mysql
          image: mysql:8.0.20
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: MYSQL_DATABASE
              value: tienda
          args:
            - --lower_case_table_names=1
            - --skip-ssl
            - --character_set_server=utf8mb4
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
              #resources:
              #            requests:
              #              memory: '512Mi'
              #              cpu: '1Gi'
              #            limits:
              #              memory: '1Gi'
              #              cpu: '2Gi'
---
apiVersion: v1
kind: Service
metadata:
  name: tienda-mysql
  namespace: jhipster
spec:
  selector:
    app: tienda-mysql
  ports:
    - port: 3306
