apiVersion: v1
kind: Service
metadata:
  name: tienda
  namespace: jhipster
  labels:
    app: tienda
spec:
  selector:
    app: tienda
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
